[package]
name = "xmount"
version = "0.1.0"
edition = "2024"

[lib]
name = "xmount"
path = "src/lib.rs"

[[bin]]
name = "xmount"
path = "src/main.rs"

[dependencies]
bitflags = "2.11.0"
log = "0.4.29"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
